// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260306194304_AddDriverModule")]
    partial class AddDriverModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Assets.AssetLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("asset_id");

                    b.Property<int>("AssetType")
                        .HasColumnType("int")
                        .HasColumnName("asset_type");

                    b.Property<bool>("IsAssigned")
                        .HasColumnType("bit")
                        .HasColumnName("is_assigned");

                    b.Property<double>("Latitude")
                        .HasColumnType("float")
                        .HasColumnName("latitude");

                    b.Property<string>("LocationName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("location_name");

                    b.Property<double>("Longitude")
                        .HasColumnType("float")
                        .HasColumnName("longitude");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("recorded_at");

                    b.Property<int>("Source")
                        .HasColumnType("int")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_asset_locations");

                    b.ToTable("asset_locations", (string)null);
                });

            modelBuilder.Entity("Domain.Assets.Trailer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("AttachedVehicleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("attached_vehicle_id");

                    b.Property<decimal>("Capacity")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("capacity");

                    b.Property<string>("CapacityUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("capacity_unit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CurrentLocationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("current_location_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalExpensesQAR")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_expenses_qar");

                    b.Property<decimal>("TotalRevenueQAR")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_revenue_qar");

                    b.Property<string>("TrailerNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("trailer_number");

                    b.Property<string>("TrailerType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("trailer_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_trailers");

                    b.HasIndex("AttachedVehicleId")
                        .HasDatabaseName("ix_trailers_attached_vehicle_id");

                    b.ToTable("trailers", (string)null);
                });

            modelBuilder.Entity("Domain.Assets.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CurrentDriverId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("current_driver_id");

                    b.Property<Guid?>("CurrentLocationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("current_location_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("make");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("model");

                    b.Property<decimal>("OdometerReading")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("odometer_reading");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("plate_number");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("registration_number");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VehicleCategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("vehicle_category_id");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_type");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_vehicles");

                    b.HasIndex("VehicleCategoryId")
                        .HasDatabaseName("ix_vehicles_vehicle_category_id");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("Domain.Assets.VehicleCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_vehicle_categories");

                    b.ToTable("vehicle_categories", (string)null);
                });

            modelBuilder.Entity("Domain.Drivers.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("employee_number");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("last_name");

                    b.Property<DateOnly>("LicenceExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("licence_expiry_date");

                    b.Property<string>("LicenceNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("licence_number");

                    b.Property<string>("NationalityCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("nationality_code");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("SponsorName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("sponsor_name");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_drivers");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_drivers_email")
                        .HasFilter("[email] IS NOT NULL");

                    b.HasIndex("EmployeeNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_drivers_employee_number");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_drivers_phone_number");

                    b.ToTable("drivers", (string)null);
                });

            modelBuilder.Entity("Domain.Drivers.DriverAttendanceLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateOnly>("AttendanceDate")
                        .HasColumnType("date")
                        .HasColumnName("attendance_date");

                    b.Property<DateTime?>("CheckInAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("check_in_at");

                    b.Property<double?>("CheckInLatitude")
                        .HasColumnType("float")
                        .HasColumnName("check_in_latitude");

                    b.Property<double?>("CheckInLongitude")
                        .HasColumnType("float")
                        .HasColumnName("check_in_longitude");

                    b.Property<DateTime?>("CheckOutAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("check_out_at");

                    b.Property<double?>("CheckOutLatitude")
                        .HasColumnType("float")
                        .HasColumnName("check_out_latitude");

                    b.Property<double?>("CheckOutLongitude")
                        .HasColumnType("float")
                        .HasColumnName("check_out_longitude");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("driver_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("notes");

                    b.Property<int>("Source")
                        .HasColumnType("int")
                        .HasColumnName("source");

                    b.Property<decimal?>("TotalHoursWorked")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("total_hours_worked");

                    b.HasKey("Id")
                        .HasName("pk_driver_attendance_logs");

                    b.HasIndex("DriverId")
                        .HasDatabaseName("ix_driver_attendance_logs_driver_id");

                    b.HasIndex("DriverId", "AttendanceDate")
                        .HasDatabaseName("ix_driver_attendance_logs_driver_id_attendance_date");

                    b.ToTable("driver_attendance_logs", (string)null);
                });

            modelBuilder.Entity("Domain.Drivers.DriverAuthCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("DeviceToken")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("device_token");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("driver_id");

                    b.Property<int>("FailedAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_attempts");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_locked");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Platform")
                        .HasColumnType("int")
                        .HasColumnName("platform");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("refresh_token_expires_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UsernameHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("username_hash");

                    b.HasKey("Id")
                        .HasName("pk_driver_auth_credentials");

                    b.HasIndex("DriverId")
                        .IsUnique()
                        .HasDatabaseName("ix_driver_auth_credentials_driver_id");

                    b.ToTable("driver_auth_credentials", (string)null);
                });

            modelBuilder.Entity("Domain.Drivers.DriverDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int")
                        .HasColumnName("document_type");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("driver_id");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("file_url");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float")
                        .HasColumnName("longitude");

                    b.Property<bool>("SubmittedFromApp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("submitted_from_app");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<Guid?>("TripId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("trip_id");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id")
                        .HasName("pk_driver_documents");

                    b.HasIndex("DriverId")
                        .HasDatabaseName("ix_driver_documents_driver_id");

                    b.ToTable("driver_documents", (string)null);
                });

            modelBuilder.Entity("Domain.Drivers.DriverExpense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountQAR")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount_qar");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("driver_id");

                    b.Property<DateOnly>("ExpenseDate")
                        .HasColumnType("date")
                        .HasColumnName("expense_date");

                    b.Property<int>("ExpenseType")
                        .HasColumnType("int")
                        .HasColumnName("expense_type");

                    b.Property<decimal?>("FuelLitres")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("fuel_litres");

                    b.Property<string>("FuelStation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("fuel_station");

                    b.Property<decimal?>("OdometerReading")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("odometer_reading");

                    b.Property<string>("ReceiptUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("receipt_url");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("submitted_at");

                    b.Property<Guid?>("TripId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("trip_id");

                    b.HasKey("Id")
                        .HasName("pk_driver_expenses");

                    b.HasIndex("DriverId")
                        .HasDatabaseName("ix_driver_expenses_driver_id");

                    b.HasIndex("TripId")
                        .HasDatabaseName("ix_driver_expenses_trip_id");

                    b.ToTable("driver_expenses", (string)null);
                });

            modelBuilder.Entity("Domain.Drivers.DriverGpsLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("driver_id");

                    b.Property<float?>("MaxSpeedKmh")
                        .HasColumnType("real")
                        .HasColumnName("max_speed_kmh");

                    b.Property<int>("PointCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("point_count");

                    b.Property<string>("RawTrackUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("raw_track_url");

                    b.Property<DateTime?>("SessionEnd")
                        .HasColumnType("datetime2")
                        .HasColumnName("session_end");

                    b.Property<DateTime>("SessionStart")
                        .HasColumnType("datetime2")
                        .HasColumnName("session_start");

                    b.Property<decimal?>("TotalDistanceKm")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_distance_km");

                    b.Property<Guid?>("TripId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("trip_id");

                    b.HasKey("Id")
                        .HasName("pk_driver_gps_logs");

                    b.HasIndex("DriverId")
                        .HasDatabaseName("ix_driver_gps_logs_driver_id");

                    b.ToTable("driver_gps_logs", (string)null);
                });

            modelBuilder.Entity("Domain.Drivers.DriverLocationUpdate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<float?>("Accuracy")
                        .HasColumnType("real")
                        .HasColumnName("accuracy");

                    b.Property<float?>("Bearing")
                        .HasColumnType("real")
                        .HasColumnName("bearing");

                    b.Property<Guid?>("DriverGpsLogId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("driver_gps_log_id");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("driver_id");

                    b.Property<double>("Latitude")
                        .HasColumnType("float")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("float")
                        .HasColumnName("longitude");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("recorded_at");

                    b.Property<int>("Source")
                        .HasColumnType("int")
                        .HasColumnName("source");

                    b.Property<float?>("SpeedKmh")
                        .HasColumnType("real")
                        .HasColumnName("speed_kmh");

                    b.Property<Guid?>("TripId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("trip_id");

                    b.HasKey("Id")
                        .HasName("pk_driver_location_updates");

                    b.HasIndex("DriverGpsLogId")
                        .HasDatabaseName("ix_driver_location_updates_driver_gps_log_id");

                    b.HasIndex("DriverId")
                        .HasDatabaseName("ix_driver_location_updates_driver_id");

                    b.HasIndex("DriverId", "RecordedAt")
                        .HasDatabaseName("ix_driver_location_updates_driver_id_recorded_at");

                    b.ToTable("driver_location_updates", (string)null);
                });

            modelBuilder.Entity("Domain.Drivers.DriverNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("body");

                    b.Property<int>("Channel")
                        .HasColumnType("int")
                        .HasColumnName("channel");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("driver_id");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<int>("NotificationType")
                        .HasColumnType("int")
                        .HasColumnName("notification_type");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("read_at");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("related_entity_id");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("related_entity_type");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("sent_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_driver_notifications");

                    b.HasIndex("DriverId")
                        .HasDatabaseName("ix_driver_notifications_driver_id");

                    b.ToTable("driver_notifications", (string)null);
                });

            modelBuilder.Entity("Domain.Drivers.DriverTripAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("accepted_at");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("assigned_at");

                    b.Property<Guid>("AssignedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("assigned_by_user_id");

                    b.Property<int>("AssignmentStatus")
                        .HasColumnType("int")
                        .HasColumnName("assignment_status");

                    b.Property<DateTime?>("DisplayedInAppAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("displayed_in_app_at");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("driver_id");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("rejected_at");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("rejection_reason");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("trip_id");

                    b.HasKey("Id")
                        .HasName("pk_driver_trip_assignments");

                    b.HasIndex("DriverId")
                        .HasDatabaseName("ix_driver_trip_assignments_driver_id");

                    b.HasIndex("TripId")
                        .HasDatabaseName("ix_driver_trip_assignments_trip_id");

                    b.ToTable("driver_trip_assignments", (string)null);
                });

            modelBuilder.Entity("Domain.Inspections.ChecklistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("category");

                    b.Property<Guid>("InspectionChecklistId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("inspection_checklist_id");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit")
                        .HasColumnName("is_required");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("item_name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_checklist_items");

                    b.HasIndex("InspectionChecklistId")
                        .HasDatabaseName("ix_checklist_items_inspection_checklist_id");

                    b.ToTable("checklist_items", (string)null);
                });

            modelBuilder.Entity("Domain.Inspections.InspectionChecklist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ApplicableVehicleTypes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("applicable_vehicle_types");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("InspectionType")
                        .HasColumnType("int")
                        .HasColumnName("inspection_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_inspection_checklists");

                    b.ToTable("inspection_checklists", (string)null);
                });

            modelBuilder.Entity("Domain.Inspections.InspectionPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Caption")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("caption");

                    b.Property<int>("PhotoType")
                        .HasColumnType("int")
                        .HasColumnName("photo_type");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("photo_url");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UploadedByDriverId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("uploaded_by_driver_id");

                    b.Property<Guid>("VehicleInspectionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("vehicle_inspection_id");

                    b.HasKey("Id")
                        .HasName("pk_inspection_photos");

                    b.HasIndex("VehicleInspectionId")
                        .HasDatabaseName("ix_inspection_photos_vehicle_inspection_id");

                    b.ToTable("inspection_photos", (string)null);
                });

            modelBuilder.Entity("Domain.Inspections.InspectionResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("ChecklistItemId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("checklist_item_id");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("bit")
                        .HasColumnName("is_passed");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("recorded_at");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("remarks");

                    b.Property<Guid>("VehicleInspectionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("vehicle_inspection_id");

                    b.HasKey("Id")
                        .HasName("pk_inspection_results");

                    b.HasIndex("ChecklistItemId")
                        .HasDatabaseName("ix_inspection_results_checklist_item_id");

                    b.HasIndex("VehicleInspectionId")
                        .HasDatabaseName("ix_inspection_results_vehicle_inspection_id");

                    b.ToTable("inspection_results", (string)null);
                });

            modelBuilder.Entity("Domain.Inspections.VehicleInspection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("driver_id");

                    b.Property<string>("DriverSignature")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("driver_signature");

                    b.Property<DateTime?>("DriverSignedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("driver_signed_at");

                    b.Property<DateTime>("InspectedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("inspected_at");

                    b.Property<Guid>("InspectionChecklistId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("inspection_checklist_id");

                    b.Property<int>("InspectionType")
                        .HasColumnType("int")
                        .HasColumnName("inspection_type");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("notes");

                    b.Property<decimal>("OdometerReading")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("odometer_reading");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<Guid?>("TripId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("trip_id");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_vehicle_inspections");

                    b.HasIndex("InspectionChecklistId")
                        .HasDatabaseName("ix_vehicle_inspections_inspection_checklist_id");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_vehicle_inspections_vehicle_id");

                    b.ToTable("vehicle_inspections", (string)null);
                });

            modelBuilder.Entity("Domain.Todos.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("due_date");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_completed");

                    b.PrimitiveCollection<string>("Labels")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("labels");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("priority");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_todo_items");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_todo_items_user_id");

                    b.ToTable("todo_items", (string)null);
                });

            modelBuilder.Entity("Domain.Trips.CustomFieldDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AppliesTo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("applies_to");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("data_type");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("default_value");

                    b.Property<string>("FieldLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("field_label");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("field_name");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("field_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit")
                        .HasColumnName("is_required");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<string>("ValidationRegex")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("validation_regex");

                    b.HasKey("Id")
                        .HasName("pk_custom_field_definitions");

                    b.ToTable("custom_field_definitions", (string)null);
                });

            modelBuilder.Entity("Domain.Trips.ImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ErrorSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("error_summary");

                    b.Property<int>("FailureCount")
                        .HasColumnType("int")
                        .HasColumnName("failure_count");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("file_name");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("int")
                        .HasColumnName("success_count");

                    b.Property<int>("TotalRows")
                        .HasColumnType("int")
                        .HasColumnName("total_rows");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_import_batches");

                    b.ToTable("import_batches", (string)null);
                });

            modelBuilder.Entity("Domain.Trips.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActualEndAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("actual_end_at");

                    b.Property<DateTime?>("ActualStartAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("actual_start_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DriverConfirmedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("driver_confirmed_at");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("driver_id");

                    b.Property<Guid?>("ImportBatchId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("import_batch_id");

                    b.Property<bool>("IsImported")
                        .HasColumnType("bit")
                        .HasColumnName("is_imported");

                    b.Property<DateTime?>("OfficeApprovedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("office_approved_at");

                    b.Property<Guid?>("OfficeApprovedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("office_approved_by_user_id");

                    b.Property<DateTime>("ScheduledStartAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("scheduled_start_at");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<decimal?>("TotalDistanceKm")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_distance_km");

                    b.Property<Guid?>("TrailerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("trailer_id");

                    b.Property<string>("TripNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("trip_number");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_trips");

                    b.HasIndex("ImportBatchId")
                        .HasDatabaseName("ix_trips_import_batch_id");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("Domain.Trips.TripCustomField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("FieldDefinitionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("field_definition_id");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("trip_id");

                    b.Property<Guid?>("TripVoucherId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("trip_voucher_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_trip_custom_fields");

                    b.HasIndex("FieldDefinitionId")
                        .HasDatabaseName("ix_trip_custom_fields_field_definition_id");

                    b.HasIndex("TripId")
                        .HasDatabaseName("ix_trip_custom_fields_trip_id");

                    b.HasIndex("TripVoucherId")
                        .HasDatabaseName("ix_trip_custom_fields_trip_voucher_id");

                    b.ToTable("trip_custom_fields", (string)null);
                });

            modelBuilder.Entity("Domain.Trips.TripHalt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("duration_minutes");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ended_at");

                    b.Property<int>("HaltType")
                        .HasColumnType("int")
                        .HasColumnName("halt_type");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float")
                        .HasColumnName("latitude");

                    b.Property<string>("LocationName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("location_name");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float")
                        .HasColumnName("longitude");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("RecordedByDriverId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("recorded_by_driver_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("started_at");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("trip_id");

                    b.HasKey("Id")
                        .HasName("pk_trip_halts");

                    b.HasIndex("TripId")
                        .HasDatabaseName("ix_trip_halts_trip_id");

                    b.ToTable("trip_halts", (string)null);
                });

            modelBuilder.Entity("Domain.Trips.TripPodUpload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int")
                        .HasColumnName("document_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("file_name");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("file_url");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float")
                        .HasColumnName("longitude");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("trip_id");

                    b.Property<Guid?>("TripStopId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("trip_stop_id");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UploadedByDriverId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("uploaded_by_driver_id");

                    b.HasKey("Id")
                        .HasName("pk_trip_pod_uploads");

                    b.HasIndex("TripId")
                        .HasDatabaseName("ix_trip_pod_uploads_trip_id");

                    b.HasIndex("TripStopId")
                        .HasDatabaseName("ix_trip_pod_uploads_trip_stop_id");

                    b.ToTable("trip_pod_uploads", (string)null);
                });

            modelBuilder.Entity("Domain.Trips.TripStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("changed_at");

                    b.Property<Guid?>("ChangedByDriverId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("changed_by_driver_id");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("changed_by_user_id");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int")
                        .HasColumnName("new_status");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("notes");

                    b.Property<int>("PreviousStatus")
                        .HasColumnType("int")
                        .HasColumnName("previous_status");

                    b.Property<int>("Source")
                        .HasColumnType("int")
                        .HasColumnName("source");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("trip_id");

                    b.HasKey("Id")
                        .HasName("pk_trip_status_histories");

                    b.HasIndex("TripId")
                        .HasDatabaseName("ix_trip_status_histories_trip_id");

                    b.ToTable("trip_status_histories", (string)null);
                });

            modelBuilder.Entity("Domain.Trips.TripStop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActualArrivalAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("actual_arrival_at");

                    b.Property<DateTime?>("ActualDepartureAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("actual_departure_at");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("address");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float")
                        .HasColumnName("latitude");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("location_name");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float")
                        .HasColumnName("longitude");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("PocEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("poc_email");

                    b.Property<string>("PocName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("poc_name");

                    b.Property<string>("PocPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("poc_phone");

                    b.Property<DateTime?>("ScheduledArrivalAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("scheduled_arrival_at");

                    b.Property<int>("StopOrder")
                        .HasColumnType("int")
                        .HasColumnName("stop_order");

                    b.Property<int>("StopType")
                        .HasColumnType("int")
                        .HasColumnName("stop_type");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("trip_id");

                    b.HasKey("Id")
                        .HasName("pk_trip_stops");

                    b.HasIndex("TripId")
                        .HasDatabaseName("ix_trip_stops_trip_id");

                    b.ToTable("trip_stops", (string)null);
                });

            modelBuilder.Entity("Domain.Trips.TripVoucher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("trip_id");

                    b.Property<DateTime>("VoucherDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("voucher_date");

                    b.Property<string>("VoucherNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("voucher_number");

                    b.HasKey("Id")
                        .HasName("pk_trip_vouchers");

                    b.HasIndex("TripId")
                        .IsUnique()
                        .HasDatabaseName("ix_trip_vouchers_trip_id");

                    b.ToTable("trip_vouchers", (string)null);
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Domain.WorkOrders.WorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal?>("ActualCostQAR")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("actual_cost_qar");

                    b.Property<Guid?>("AssignedTechnicianId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("assigned_technician_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("description");

                    b.Property<decimal?>("EstimatedCostQAR")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("estimated_cost_qar");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("priority");

                    b.Property<DateTime?>("ScheduledDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("scheduled_date");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("vehicle_id");

                    b.Property<Guid?>("VehicleInspectionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("vehicle_inspection_id");

                    b.Property<string>("WorkOrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("work_order_number");

                    b.HasKey("Id")
                        .HasName("pk_work_orders");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_work_orders_vehicle_id");

                    b.HasIndex("VehicleInspectionId")
                        .HasDatabaseName("ix_work_orders_vehicle_inspection_id");

                    b.ToTable("work_orders", (string)null);
                });

            modelBuilder.Entity("Domain.WorkOrders.WorkOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<int>("ItemType")
                        .HasColumnType("int")
                        .HasColumnName("item_type");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("TotalCostQAR")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_cost_qar");

                    b.Property<decimal>("UnitCostQAR")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_cost_qar");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("work_order_id");

                    b.HasKey("Id")
                        .HasName("pk_work_order_items");

                    b.HasIndex("WorkOrderId")
                        .HasDatabaseName("ix_work_order_items_work_order_id");

                    b.ToTable("work_order_items", (string)null);
                });

            modelBuilder.Entity("Domain.WorkOrders.WorkOrderStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("changed_at");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("changed_by_user_id");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int")
                        .HasColumnName("new_status");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("notes");

                    b.Property<int>("PreviousStatus")
                        .HasColumnType("int")
                        .HasColumnName("previous_status");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("work_order_id");

                    b.HasKey("Id")
                        .HasName("pk_work_order_status_histories");

                    b.HasIndex("WorkOrderId")
                        .HasDatabaseName("ix_work_order_status_histories_work_order_id");

                    b.ToTable("work_order_status_histories", (string)null);
                });

            modelBuilder.Entity("Domain.Assets.Trailer", b =>
                {
                    b.HasOne("Domain.Assets.Vehicle", "AttachedVehicle")
                        .WithMany()
                        .HasForeignKey("AttachedVehicleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_trailers_vehicles_attached_vehicle_id");

                    b.Navigation("AttachedVehicle");
                });

            modelBuilder.Entity("Domain.Assets.Vehicle", b =>
                {
                    b.HasOne("Domain.Assets.VehicleCategory", "Category")
                        .WithMany("Vehicles")
                        .HasForeignKey("VehicleCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehicles_vehicle_categories_vehicle_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Drivers.DriverAttendanceLog", b =>
                {
                    b.HasOne("Domain.Drivers.Driver", "Driver")
                        .WithMany("AttendanceLogs")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_driver_attendance_logs_drivers_driver_id");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("Domain.Drivers.DriverAuthCredential", b =>
                {
                    b.HasOne("Domain.Drivers.Driver", "Driver")
                        .WithOne("AuthCredential")
                        .HasForeignKey("Domain.Drivers.DriverAuthCredential", "DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_driver_auth_credentials_drivers_driver_id");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("Domain.Drivers.DriverDocument", b =>
                {
                    b.HasOne("Domain.Drivers.Driver", "Driver")
                        .WithMany("Documents")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_driver_documents_drivers_driver_id");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("Domain.Drivers.DriverExpense", b =>
                {
                    b.HasOne("Domain.Drivers.Driver", "Driver")
                        .WithMany("Expenses")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_driver_expenses_drivers_driver_id");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("Domain.Drivers.DriverGpsLog", b =>
                {
                    b.HasOne("Domain.Drivers.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_driver_gps_logs_drivers_driver_id");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("Domain.Drivers.DriverLocationUpdate", b =>
                {
                    b.HasOne("Domain.Drivers.DriverGpsLog", null)
                        .WithMany("LocationUpdates")
                        .HasForeignKey("DriverGpsLogId")
                        .HasConstraintName("fk_driver_location_updates_driver_gps_logs_driver_gps_log_id");

                    b.HasOne("Domain.Drivers.Driver", "Driver")
                        .WithMany("LocationUpdates")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_driver_location_updates_drivers_driver_id");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("Domain.Drivers.DriverNotification", b =>
                {
                    b.HasOne("Domain.Drivers.Driver", "Driver")
                        .WithMany("Notifications")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_driver_notifications_drivers_driver_id");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("Domain.Drivers.DriverTripAssignment", b =>
                {
                    b.HasOne("Domain.Drivers.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_driver_trip_assignments_drivers_driver_id");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("Domain.Inspections.ChecklistItem", b =>
                {
                    b.HasOne("Domain.Inspections.InspectionChecklist", "InspectionChecklist")
                        .WithMany("Items")
                        .HasForeignKey("InspectionChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_checklist_items_inspection_checklists_inspection_checklist_id");

                    b.Navigation("InspectionChecklist");
                });

            modelBuilder.Entity("Domain.Inspections.InspectionPhoto", b =>
                {
                    b.HasOne("Domain.Inspections.VehicleInspection", "VehicleInspection")
                        .WithMany("Photos")
                        .HasForeignKey("VehicleInspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inspection_photos_vehicle_inspections_vehicle_inspection_id");

                    b.Navigation("VehicleInspection");
                });

            modelBuilder.Entity("Domain.Inspections.InspectionResult", b =>
                {
                    b.HasOne("Domain.Inspections.ChecklistItem", "ChecklistItem")
                        .WithMany()
                        .HasForeignKey("ChecklistItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inspection_results_checklist_items_checklist_item_id");

                    b.HasOne("Domain.Inspections.VehicleInspection", "VehicleInspection")
                        .WithMany("InspectionResults")
                        .HasForeignKey("VehicleInspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inspection_results_vehicle_inspections_vehicle_inspection_id");

                    b.Navigation("ChecklistItem");

                    b.Navigation("VehicleInspection");
                });

            modelBuilder.Entity("Domain.Inspections.VehicleInspection", b =>
                {
                    b.HasOne("Domain.Inspections.InspectionChecklist", "InspectionChecklist")
                        .WithMany()
                        .HasForeignKey("InspectionChecklistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_inspections_inspection_checklists_inspection_checklist_id");

                    b.HasOne("Domain.Assets.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_inspections_vehicles_vehicle_id");

                    b.Navigation("InspectionChecklist");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Domain.Todos.TodoItem", b =>
                {
                    b.HasOne("Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_todo_items_users_user_id");
                });

            modelBuilder.Entity("Domain.Trips.Trip", b =>
                {
                    b.HasOne("Domain.Trips.ImportBatch", null)
                        .WithMany("ImportedTrips")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_trips_import_batches_import_batch_id");
                });

            modelBuilder.Entity("Domain.Trips.TripCustomField", b =>
                {
                    b.HasOne("Domain.Trips.CustomFieldDefinition", "FieldDefinition")
                        .WithMany()
                        .HasForeignKey("FieldDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trip_custom_fields_custom_field_definitions_field_definition_id");

                    b.HasOne("Domain.Trips.Trip", "Trip")
                        .WithMany("CustomFields")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trip_custom_fields_trips_trip_id");

                    b.HasOne("Domain.Trips.TripVoucher", null)
                        .WithMany("CustomFields")
                        .HasForeignKey("TripVoucherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_trip_custom_fields_trip_vouchers_trip_voucher_id");

                    b.Navigation("FieldDefinition");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Domain.Trips.TripHalt", b =>
                {
                    b.HasOne("Domain.Trips.Trip", "Trip")
                        .WithMany("Halts")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trip_halts_trips_trip_id");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Domain.Trips.TripPodUpload", b =>
                {
                    b.HasOne("Domain.Trips.Trip", "Trip")
                        .WithMany("PodUploads")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trip_pod_uploads_trips_trip_id");

                    b.HasOne("Domain.Trips.TripStop", "TripStop")
                        .WithMany("PodUploads")
                        .HasForeignKey("TripStopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_trip_pod_uploads_trip_stops_trip_stop_id");

                    b.Navigation("Trip");

                    b.Navigation("TripStop");
                });

            modelBuilder.Entity("Domain.Trips.TripStatusHistory", b =>
                {
                    b.HasOne("Domain.Trips.Trip", "Trip")
                        .WithMany("StatusHistory")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trip_status_histories_trips_trip_id");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Domain.Trips.TripStop", b =>
                {
                    b.HasOne("Domain.Trips.Trip", "Trip")
                        .WithMany("Stops")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trip_stops_trips_trip_id");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Domain.Trips.TripVoucher", b =>
                {
                    b.HasOne("Domain.Trips.Trip", "Trip")
                        .WithOne("Voucher")
                        .HasForeignKey("Domain.Trips.TripVoucher", "TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trip_vouchers_trips_trip_id");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Domain.WorkOrders.WorkOrder", b =>
                {
                    b.HasOne("Domain.Assets.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_work_orders_vehicles_vehicle_id");

                    b.HasOne("Domain.Inspections.VehicleInspection", "VehicleInspection")
                        .WithMany()
                        .HasForeignKey("VehicleInspectionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_work_orders_vehicle_inspections_vehicle_inspection_id");

                    b.Navigation("Vehicle");

                    b.Navigation("VehicleInspection");
                });

            modelBuilder.Entity("Domain.WorkOrders.WorkOrderItem", b =>
                {
                    b.HasOne("Domain.WorkOrders.WorkOrder", "WorkOrder")
                        .WithMany("WorkOrderItems")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_order_items_work_orders_work_order_id");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("Domain.WorkOrders.WorkOrderStatusHistory", b =>
                {
                    b.HasOne("Domain.WorkOrders.WorkOrder", "WorkOrder")
                        .WithMany("StatusHistory")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_order_status_histories_work_orders_work_order_id");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("Domain.Assets.VehicleCategory", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Domain.Drivers.Driver", b =>
                {
                    b.Navigation("AttendanceLogs");

                    b.Navigation("AuthCredential");

                    b.Navigation("Documents");

                    b.Navigation("Expenses");

                    b.Navigation("LocationUpdates");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Domain.Drivers.DriverGpsLog", b =>
                {
                    b.Navigation("LocationUpdates");
                });

            modelBuilder.Entity("Domain.Inspections.InspectionChecklist", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Domain.Inspections.VehicleInspection", b =>
                {
                    b.Navigation("InspectionResults");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Domain.Trips.ImportBatch", b =>
                {
                    b.Navigation("ImportedTrips");
                });

            modelBuilder.Entity("Domain.Trips.Trip", b =>
                {
                    b.Navigation("CustomFields");

                    b.Navigation("Halts");

                    b.Navigation("PodUploads");

                    b.Navigation("StatusHistory");

                    b.Navigation("Stops");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("Domain.Trips.TripStop", b =>
                {
                    b.Navigation("PodUploads");
                });

            modelBuilder.Entity("Domain.Trips.TripVoucher", b =>
                {
                    b.Navigation("CustomFields");
                });

            modelBuilder.Entity("Domain.WorkOrders.WorkOrder", b =>
                {
                    b.Navigation("StatusHistory");

                    b.Navigation("WorkOrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
