name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image
      run: |
        docker build . --file src/Web.Api \
          --tag ${{ secrets.DOCKERHUB_USERNAME }}/web-api:latest \
          --tag ${{ secrets.DOCKERHUB_USERNAME }}/web-api:${{ github.sha }}

    - name: Push the Docker image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/web-api:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/web-api:${{ github.sha }}
